# Create a GitHub Actions workflow for continuous deployment that deploys to staging and production environments with proper approvals
name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to staging
        run: echo "Deploying to staging..."

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://myapp.prod.com
    steps:
      - name: Await manual approval
        uses: hmarr/auto-approve-action@v2
      - name: Deploy to production
        run: echo "Deploying to production..."
